maxBeads = 500
matchPenalty = -0.1
reEvaluation = 5
displayGraph = False
maxReEvaluation = 10
sampleUntilMeanConvergence = False
standardErrorThreshold = 0.01
maxTimeEval = 501
target = center
width = 0.3
